name = "plinkoreview-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=plinkoreview.fr"
HMAC_KEY = "74f7092df345bc5dddc7d4d8eb910c2c6b865dbfa5d9f92b9bc0d61eec160dfd"
COOKIE_NAME = "02r"
PLAY_PATH = "join-now"
BUTTON_ID = "pe5e537049d2fb8db834ce5435198e172"
GATE_SALT = "5ed849efacf07d36"
